if (GetLocale() == "koKR") then
	-- Class Names
	KGMM_LOCALIZED_DRUID = "드루이드";
	KGMM_LOCALIZED_HUNTER = "사냥꾼";
	KGMM_LOCALIZED_MAGE = "마법사";
	KGMM_LOCALIZED_PALADIN = "성기사";
	KGMM_LOCALIZED_PRIEST = "사제";
	KGMM_LOCALIZED_ROGUE = "도적";
	KGMM_LOCALIZED_SHAMAN = "주술사";
	KGMM_LOCALIZED_WARLOCK = "흑마법사";
	KGMM_LOCALIZED_WARRIOR = "전사";

end