if (GetLocale() == "enUS") then

kBar_NAMES = {"kBar1","kBar2","kBar3","kBar4","Left","Right","BRight","BLeft","Main2","Main","Pet","Bag","Help","Shape","XP","Remind"}

kBarOPTION_TITLE		= "kBar Option"
kBarOPTION_SELECTBAR	= "Select Bar"
kBarOPTION_ATTRIBUTE	= "Attribute"
kBarOPTION_RESET    = "Reset Position"

kBar_ATTR_HIDE = "Hide"
kBar_ATTR_NAME = "Name"
kBar_ATTR_LOCK = "Lock"
kBar_ATTR_AUTOALPHA = "Alpha"
kBar_ATTR_AOTUPOP = "AutoPop"
kBar_ATTR_AOTUHIDE = "AutoHide"
kBar_ATTR_FUNNY1 = "Funny1"
kBar_ATTR_FUNNY2 = "Funny2"
kBar_ATTR_HOTKEY = "Hide Hotkeys"
kBar_ATTR_LOCKBUTTON = "Lock All Butons"
kBar_ATTR_HIDEGRID = "Hide Empty Buttons"

kBar_SLIDER_SCALE = "Scale"
kBar_SLIDER_INSECT = "Button Spacing"
kBar_SLIDER_NUM = "Num of Buttons"
kBar_SLIDER_NUMPERLINE = "Num per Line"

kBar_TIP_HIDE		= "Show / Hide this bar"
kBar_TIP_NAME		= "Show / Hide name of this bar"
kBar_TIP_LOCK		= "Lock bar and hide tab"
kBar_TIP_AOTUALPHA   = "Alpha when mouse leave, Normal when enter"
kBar_TIP_AOTUPOP	  = "Pop up when Targeting Enemy or In Combat, Hide otherwise"
kBar_TIP_AOTUHIDE     = "Hide in combat, show after"
kBar_TIP_FUNNY1         = "Arrangement 1"
kBar_TIP_FUNNY2         = "Arrangement 2"
kBar_TIP_HOTKEY         = "Show / Hide Hotkeys for this bar"
kBar_TIP_LOCKBUTTON = "Lock All Buttons"
kBar_TIP_HIDEGRID       = "Hide Empty Buttons"

kBar_TIP_SCALE		= "Drag slider, Change Scale to appropriate size"
kBar_TIP_NUM		= "Number of Buttons to show in bar"
kBar_TIP_NUMPERLINE	= "Set Number of Buttons per Line\nMake Arrangements of Vertical / Horizontal / Multi Line"
kBar_TIP_INSECT		= "Adjust button spacing"

--[[ Bindings ]]--

BINDING_HEADER_kBar = "kBar Bindings"

BINDING_NAME_ACTIONBUTTON109 = "kBar1 Button1"
BINDING_NAME_ACTIONBUTTON110 = "kBar1 Button2"
BINDING_NAME_ACTIONBUTTON111 = "kBar1 Button3"
BINDING_NAME_ACTIONBUTTON112 = "kBar1 Button4"
BINDING_NAME_ACTIONBUTTON113 = "kBar1 Button5"
BINDING_NAME_ACTIONBUTTON114 = "kBar1 Button6"
BINDING_NAME_ACTIONBUTTON115 = "kBar1 Button7"
BINDING_NAME_ACTIONBUTTON116 = "kBar1 Button8"
BINDING_NAME_ACTIONBUTTON117 = "kBar1 Button9"
BINDING_NAME_ACTIONBUTTON118 = "kBar1 Button10"
BINDING_NAME_ACTIONBUTTON119 = "kBar1 Button11"
BINDING_NAME_ACTIONBUTTON120 = "kBar1 Button12"

BINDING_NAME_ACTIONBUTTON97 = "kBar2 Button1"
BINDING_NAME_ACTIONBUTTON98 = "kBar2 Button2"
BINDING_NAME_ACTIONBUTTON99 = "kBar2 Button3"
BINDING_NAME_ACTIONBUTTON100 = "kBar2 Button4"
BINDING_NAME_ACTIONBUTTON101 = "kBar2 Button5"
BINDING_NAME_ACTIONBUTTON102 = "kBar2 Button6"
BINDING_NAME_ACTIONBUTTON103 = "kBar2 Button7"
BINDING_NAME_ACTIONBUTTON104 = "kBar2 Button8"
BINDING_NAME_ACTIONBUTTON105 = "kBar2 Button9"
BINDING_NAME_ACTIONBUTTON106 = "kBar2 Button10"
BINDING_NAME_ACTIONBUTTON107 = "kBar2 Button11"
BINDING_NAME_ACTIONBUTTON108 = "kBar2 Button12"

BINDING_NAME_ACTIONBUTTON85 = "kBar3 Button1"
BINDING_NAME_ACTIONBUTTON86 = "kBar3 Button2"
BINDING_NAME_ACTIONBUTTON87 = "kBar3 Button3"
BINDING_NAME_ACTIONBUTTON88 = "kBar3 Button4"
BINDING_NAME_ACTIONBUTTON89 = "kBar3 Button5"
BINDING_NAME_ACTIONBUTTON90 = "kBar3 Button6"
BINDING_NAME_ACTIONBUTTON91 = "kBar3 Button7"
BINDING_NAME_ACTIONBUTTON92 = "kBar3 Button8"
BINDING_NAME_ACTIONBUTTON93 = "kBar3 Button9"
BINDING_NAME_ACTIONBUTTON94 = "kBar3 Button10"
BINDING_NAME_ACTIONBUTTON95 = "kBar3 Button11"
BINDING_NAME_ACTIONBUTTON96 = "kBar3 Button12"

BINDING_NAME_ACTIONBUTTON73 = "kBar4 Button1"
BINDING_NAME_ACTIONBUTTON74 = "kBar4 Button2"
BINDING_NAME_ACTIONBUTTON75 = "kBar4 Button3"
BINDING_NAME_ACTIONBUTTON76 = "kBar4 Button4"
BINDING_NAME_ACTIONBUTTON77 = "kBar4 Button5"
BINDING_NAME_ACTIONBUTTON78 = "kBar4 Button6"
BINDING_NAME_ACTIONBUTTON79 = "kBar4 Button7"
BINDING_NAME_ACTIONBUTTON80 = "kBar4 Button8"
BINDING_NAME_ACTIONBUTTON81 = "kBar4 Button9"
BINDING_NAME_ACTIONBUTTON82 = "kBar4 Button10"
BINDING_NAME_ACTIONBUTTON83 = "kBar4 Button11"
BINDING_NAME_ACTIONBUTTON84 = "kBar4 Button12"

BINDING_NAME_ACTIONBUTTON13 = "Main2 Button1"
BINDING_NAME_ACTIONBUTTON14 = "Main2 Button2"
BINDING_NAME_ACTIONBUTTON15 = "Main2 Button3"
BINDING_NAME_ACTIONBUTTON16 = "Main2 Button4"
BINDING_NAME_ACTIONBUTTON17 = "Main2 Button5"
BINDING_NAME_ACTIONBUTTON18 = "Main2 Button6"
BINDING_NAME_ACTIONBUTTON19 = "Main2 Button7"
BINDING_NAME_ACTIONBUTTON20 = "Main2 Button8"
BINDING_NAME_ACTIONBUTTON21 = "Main2 Button9"
BINDING_NAME_ACTIONBUTTON22 = "Main2 Button10"
BINDING_NAME_ACTIONBUTTON23 = "Main2 Button11"
BINDING_NAME_ACTIONBUTTON24 = "Main2 Button12"

end 